### ISSUE TITLE
Low fps and hotbar setting disappearingn

### ISSUE THREAD

**Issue by cat-xiv** [grittyfrog/MacroMate#9] opened 2024-05-13 16:54 UTC
I have a lot of macros saved and yesterady I noticed my game beign pretty laggy. /xlstats says the ConditionManager takes a whole bunch of time to process.

which is to be expected if i have a lot of macros it needs to check.

so i'd suggest either not checking all macros on each single frame. either only on certain events. 
or have the check offloaded onto another thread so the mainthread isnt halted. 

xlstats:
every macro having an Area||Job||PvPState check take ~2.5ms 
every macro being always linked  take ~2.0ms

Also i noticed my  hotbars being fully sometimes, which stopped since deactivating MacroMate so i think it might be somehow related?

**Comment by grittyfrog** [comment] 2024-05-14 01:34
Macro Mate should only check the tree when the conditions change, so I'm not sure exactly what is causing the problem, but I'll take a look this week and see if anything stands out.

Thanks for the feedback 🙂

**Comment by grittyfrog** [comment] 2024-05-14 03:36
Huh that is extremely weird, is there any specific behaviour that seems to trigger it? I'll do some digging but the first step will be to reproduce the issue locally

**Comment by Uriei** [comment] 2024-05-14 07:39
I confirm that I've also had some of those issues, this morning both my hotbars and macros were gone, all of them, also those files being constantly created and removed, well, not all of them removed
![image](https://github.com/grittyfrog/MacroMate/assets/6078221/22a204e8-9afb-4167-a48f-fb2dad1e755a)

**Comment by grittyfrog** [comment] 2024-05-14 09:00
Hmm that's very weird, I'll dig into this soon and figure out what's going on :thinking:

**Comment by grittyfrog** [comment] 2024-05-14 09:23
I haven't been able to reproduce this issue locally, though I'll keep an eye on it in case it pops up. 

With that said, I've had a bit of a think of _possible_ root causes and there was a bit of code from the early days of Macro Mate which might trigger this sort of behavior, but is also unnecessary. I've deleted it and will be releasing version `1.0.10.2` shortly. 

The new version will be available once https://github.com/goatcorp/DalamudPluginsD17/pull/3514 is merged and _might_ solve the hotbar issues.

If you are experiencing the hotbar issue please:

- Update to `1.0.10.2`
- If you're still experiencing the issue, let me know and try to include a `dalamud.log` and any context that might help me reproduce it

**Comment by grittyfrog** [comment] 2024-05-15 01:11
After more investigation it seems that the macro tree _was_ being refreshed every frame due to a bug relating to `PlayerCondition`.

This should be fixed in `1.0.10.3` by https://github.com/grittyfrog/MacroMate/commit/ca157e018cd76c140a411fe43ba4aaacf8ccb7c0. You'll be able to access it via Dalamud once https://github.com/goatcorp/DalamudPluginsD17/pull/3516 is merged.

Hopefully the combination of changes resolves both issues. Please let me know if you see an improvement or if you're still suffering the same issue after updating to `1.0.10.3`

**Comment by Uriei** [comment] 2024-05-15 06:35
Nice, still I have to add that I've found another reason for my problem with thousand of files, I had set my Google Drive to make a backup of my user Documents folder, but as this game is dumb enough to store these files in that folder, I can't understand many games feel the need to store game files in a Documents folder!, so I guess that gDrive was locking those files being created and MM couldn't delete them sometimes, and they just built up. Sadly I'll have to remove my gDrive from doing backups of the Documents folder anyways, I blame SE for deciding to put it there...

**Comment by Uriei** [comment] 2024-05-15 09:32
Oh well, it just happened again, and this time I had no gDrive on
![image](https://github.com/grittyfrog/MacroMate/assets/6078221/46246ced-409e-44a2-80fd-0ec4cd599b03)
![image](https://github.com/grittyfrog/MacroMate/assets/6078221/d09ff3e7-9a7a-4c9d-8183-7572f849eeae)

**Comment by grittyfrog** [comment] 2024-05-15 09:49
That's super weird, there basically isn't any code left in Macro Mate that should trigger any config changes. I'll keep an eye out but so far I haven't been able to reproduce that issue. (Might be caused by spamming `SetMacro`? Let me know if it happens again in `1.0.10.3`)

Did the issue occur on version `1.0.10.2`?

**Comment by Uriei** [comment] 2024-05-15 09:51
![image](https://github.com/grittyfrog/MacroMate/assets/6078221/7f1e60bc-51ac-4ffd-9097-3976b061308b)
I'll update now and see ty

**Comment by kira-nyx** [comment] 2024-05-15 22:48
I'll update and keep an eye out! For anyone having this issue and doesn't wanna risk losing all your setup, I highly recommend getting JustBackup set up, I only was able to recover my stuff because of it

**Comment by grittyfrog** [comment] 2024-05-18 02:47
In the absence of more issue reports I'm going to mark this as resolved by version `v1.0.10.3`. 

Please let me know if you see this issue occur in the version or later. If it does I'm happy to re-open and investigate.

**Closed by grittyfrog** 2024-05-18 02:47 UTC
Labels: bug
